# Title : 多層感知器 (Multilayer Perceptron, MLP)
# File : multilayer_perceptron_iris.ipynb
# Author  : Ming-Chang Lee
# Date : 2023.11.27
# Email : alan9956@gmail.com
# YouTube : https://www.youtube.com/@alan9956
# RWEPA : http://rwepa.blogspot.tw/
# GitHub : https://github.com/rwepa

In [1]:
# 安裝 tensorflow 模組 
# pip install tensorflow

# 顯示 tensorflow 安裝版本
# conda list tensorflow

# MLP 六大步驟

+ 步驟1 載入套件
+ 步驟2 資料預處理
+ 步驟3 定義模型
+ 步驟4 編譯模型
+ 步驟5 訓練模型
+ 步驟6 評估與儲存模型

# 步驟1 載入套件

In [2]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
# WARNING: The name tf.losses.sparse_softmax_cross_entropy is deprecated. 
# Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

# 步驟2 資料預處理

In [3]:
# 設定亂數種子
np.random.seed(123)

In [4]:
# 載入資料集
# https://github.com/rwepa/DataDemo/blob/master/iris.csv
# df = pd.read_csv("iris.csv")

urls = "https://raw.githubusercontent.com/rwepa/DataDemo/master/iris.csv"
df = pd.read_csv(urls)
df

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
# one-hot 編碼
target_mapping = {"setosa": 0,
                  "versicolor": 1,
                  "virginica": 2}

df["Species"] = df["Species"].map(target_mapping)
df

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [6]:
dataset = df.values # 取出資料框的值
np.random.shuffle(dataset)  # 使用亂數打亂資料的列順序

In [7]:
# 分割成特徵資料(X)和標籤資料(Y)
X = dataset[:,0:4].astype(float)
print(X)

[[6.3 2.5 4.9 1.5]
 [6.8 3.  5.5 2.1]
 [6.4 2.8 5.6 2.2]
 [5.6 3.  4.1 1.3]
 [4.9 3.6 1.4 0.1]
 [6.  3.  4.8 1.8]
 [6.3 2.3 4.4 1.3]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [5.5 2.6 4.4 1.2]
 [6.9 3.1 5.1 2.3]
 [5.5 4.2 1.4 0.2]
 [5.2 2.7 3.9 1.4]
 [6.5 3.  5.5 1.8]
 [7.7 3.  6.1 2.3]
 [6.5 3.  5.8 2.2]
 [5.5 3.5 1.3 0.2]
 [4.3 3.  1.1 0.1]
 [6.1 2.9 4.7 1.4]
 [4.8 3.  1.4 0.3]
 [5.2 3.4 1.4 0.2]
 [6.3 2.8 5.1 1.5]
 [4.8 3.4 1.9 0.2]
 [6.1 3.  4.9 1.8]
 [5.1 3.8 1.6 0.2]
 [5.4 3.4 1.7 0.2]
 [5.4 3.4 1.5 0.4]
 [5.6 2.8 4.9 2. ]
 [7.7 3.8 6.7 2.2]
 [5.  3.6 1.4 0.2]
 [7.4 2.8 6.1 1.9]
 [6.  2.2 5.  1.5]
 [4.7 3.2 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [6.  2.2 4.  1. ]
 [5.  2.3 3.3 1. ]
 [7.9 3.8 6.4 2. ]
 [5.4 3.9 1.7 0.4]
 [5.4 3.9 1.3 0.4]
 [5.8 2.7 3.9 1.2]
 [5.  2.  3.5 1. ]
 [5.  3.2 1.2 0.2]
 [6.8 3.2 5.9 2.3]
 [6.7 3.  5.2 2.3]
 [5.8 2.7 5.1 1.9]
 [5.8 2.8 5.1 2.4]
 [6.3 3.4 5.6 2.4]
 [5.5 2.3 4.  1.3]
 [5.1 3.8 1.5 0.3]
 [4.4 3.  1.3 0.2]
 [6.5 3.2 5.1 2. ]
 [5.1 3.3 1.7 0.5]
 [4.9 3.1 1.

In [8]:
print(X.shape)

(150, 4)


In [9]:
dataset[:,4]

array([1., 2., 2., 1., 0., 2., 1., 0., 0., 1., 2., 0., 1., 2., 2., 2., 0.,
       0., 1., 0., 0., 2., 0., 2., 0., 0., 0., 2., 2., 0., 2., 2., 0., 0.,
       1., 1., 2., 0., 0., 1., 1., 0., 2., 2., 2., 2., 2., 1., 0., 0., 2.,
       0., 0., 1., 1., 1., 1., 2., 1., 2., 0., 2., 1., 0., 0., 2., 1., 2.,
       2., 0., 1., 1., 2., 0., 2., 1., 1., 0., 2., 2., 0., 0., 1., 1., 2.,
       0., 0., 1., 0., 1., 2., 0., 2., 0., 0., 1., 0., 0., 1., 2., 1., 1.,
       1., 0., 0., 1., 2., 0., 0., 1., 1., 1., 2., 1., 1., 1., 2., 0., 0.,
       1., 2., 2., 2., 2., 0., 1., 0., 1., 1., 0., 1., 2., 1., 2., 2., 0.,
       1., 0., 2., 2., 1., 1., 2., 2., 1., 0., 1., 1., 2., 2.])

In [10]:
Y = to_categorical(dataset[:,4])
print(Y)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0.

In [11]:
print(Y.shape)

(150, 3)


In [12]:
# 特徵標準化
X -= X.mean(axis=0)
X /= X.std(axis=0)

In [13]:
# 分割成訓練和測試資料集
X_train, Y_train = X[:120], Y[:120]     # 訓練資料前120筆

In [14]:
X_train

array([[ 5.53333275e-01, -1.28296331e+00,  6.49083415e-01,
         3.95774101e-01],
       [ 1.15917263e+00, -1.31979479e-01,  9.90107977e-01,
         1.18556721e+00],
       [ 6.74501145e-01, -5.92373012e-01,  1.04694540e+00,
         1.31719939e+00],
       [-2.94841818e-01, -1.31979479e-01,  1.94384000e-01,
         1.32509732e-01],
       [-1.14301691e+00,  1.24920112e+00, -1.34022653e+00,
        -1.44707648e+00],
       [ 1.89829664e-01, -1.31979479e-01,  5.92245988e-01,
         7.90670654e-01],
       [ 5.53333275e-01, -1.74335684e+00,  3.64896281e-01,
         1.32509732e-01],
       [-1.74885626e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-4.16009689e-01, -1.05276654e+00,  3.64896281e-01,
         8.77547895e-04],
       [ 1.28034050e+00,  9.82172869e-02,  7.62758269e-01,
         1.44883158e+00],
       [-4.16009689e-01,  2.63038172e+00, -1.34022653e+00,
      

In [15]:
X_train.shape

(120, 4)

In [16]:
Y_train

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1

In [17]:
Y_train.shape

(120, 3)

In [18]:
X_test, Y_test = X[120:], Y[120:]       # 測試資料後30筆

In [19]:
X_test

array([[ 1.28034050e+00,  3.28414053e-01,  1.10378283e+00,
         1.44883158e+00],
       [ 6.74501145e-01,  9.82172869e-02,  9.90107977e-01,
         7.90670654e-01],
       [ 1.64384411e+00,  3.28414053e-01,  1.27429511e+00,
         7.90670654e-01],
       [ 7.95669016e-01, -1.31979479e-01,  8.19595696e-01,
         1.05393502e+00],
       [-9.00681170e-01,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-5.37177559e-01, -1.31979479e-01,  4.21733708e-01,
         3.95774101e-01],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-5.25060772e-02, -8.22569778e-01,  1.94384000e-01,
        -2.62386821e-01],
       [-1.73673948e-01, -5.92373012e-01,  4.21733708e-01,
         1.32509732e-01],
       [-1.02184904e+00,  5.58610819e-01, -1.34022653e+00,
        -1.31544430e+00],
       [ 4.32165405e-01, -1.97355361e+00,  4.21733708e-01,
         3.95774101e-01],
       [ 1.03800476e+00,  9.82172869e-02,  1.04694540e+00,
      

In [20]:
print(X_test.shape)

(30, 4)


In [21]:
Y_test

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

# 步驟3 定義模型

In [22]:
# 建立Keras Sequential模型
# input(4)-->hiden1(6)-->hiden2(6)-->output(3)
# 輸入層 4個特徵
# 第1隱藏層 6個神經元
# 第2隱藏層 6個神經元
# 輸出層 3個神經元

model = Sequential() # 建立 Sequential 物件
model.add(Dense(6, input_shape=(4,), activation="relu"))
model.add(Dense(6, activation="relu"))
model.add(Dense(3, activation="softmax"))
model.summary()   # 顯示模型摘要
# WARNING: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

# dense (Dense)   : 4*6 + 6 = 30
# dense_1 (Dense) : 6*6 + 6 = 42
# dense_2 (Dense) : 6*3 + 3 = 21
# 合計 = 30 + 42 + 21 = 93


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 30        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 3)                 21        
                                                                 
Total params: 93 (372.00 Byte)
Trainable params: 93 (372.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# 步驟4 編譯模型

In [23]:
# 編譯模型
# loss 損失函數, 使用"類別型交叉熵"
# optimizer 優化器即梯度下降法, 使用 adam
# metrics 評估標準, 使用 accuracy 正確率
# https://www.tensorflow.org/api_docs/python/tf/keras/optimizers

model.compile(loss="categorical_crossentropy", 
              optimizer="adam",
              metrics=["accuracy"])

# WARNING: The name tf.train.Optimizer is deprecated. 
# Please use tf.compat.v1.train.Optimizer instead.

# 步驟5 訓練模型

In [24]:
# epochs 訓練週期,  batch_size 批次樣本大小, 本步驟需一些時間

print("Training ...")
model.fit(X_train, Y_train, epochs=100, batch_size=5)

Training ...
Epoch 1/100


24/24 [==============================] - 3s 4ms/step - loss: 0.9174 - accuracy: 0.4667
Epoch 2/100
24/24 [==============================] - 0s 3ms/step - loss: 0.8528 - accuracy: 0.5083
Epoch 3/100
24/24 [==============================] - 0s 4ms/step - loss: 0.8039 - accuracy: 0.5833
Epoch 4/100
24/24 [==============================] - 0s 3ms/step - loss: 0.7670 - accuracy: 0.6417
Epoch 5/100
24/24 [==============================] - 0s 3ms/step - loss: 0.7381 - accuracy: 0.6583
Epoch 6/100
24/24 [==============================] - 0s 3ms/step - loss: 0.7133 - accuracy: 0.6833
Epoch 7/100
24/24 [==============================] - 0s 3ms/step - loss: 0.6909 - accuracy: 0.6917
Epoch 8/100
24/24 [==============================] - 0s 3ms/step - loss: 0.6700 - accuracy: 0.7333
Epoch 9/100
24/24 [==============================] - 0s 4ms/step - loss: 0.6472 - accuracy: 0.7583
Epoch 10/100
24/24 [==============================] - 0s 3ms/step - loss: 0.6233 - accuracy: 0

24/24 [==============================] - 0s 3ms/step - loss: 0.0510 - accuracy: 0.9917
Epoch 79/100
24/24 [==============================] - 0s 3ms/step - loss: 0.0503 - accuracy: 0.9917
Epoch 80/100
24/24 [==============================] - 0s 3ms/step - loss: 0.0502 - accuracy: 0.9917
Epoch 81/100
24/24 [==============================] - 0s 3ms/step - loss: 0.0488 - accuracy: 0.9917
Epoch 82/100
24/24 [==============================] - 0s 3ms/step - loss: 0.0487 - accuracy: 0.9917
Epoch 83/100
24/24 [==============================] - 0s 3ms/step - loss: 0.0493 - accuracy: 0.9833
Epoch 84/100
24/24 [==============================] - 0s 3ms/step - loss: 0.0466 - accuracy: 0.9917
Epoch 85/100
24/24 [==============================] - 0s 3ms/step - loss: 0.0462 - accuracy: 0.9917
Epoch 86/100
24/24 [==============================] - 0s 3ms/step - loss: 0.0454 - accuracy: 0.9917
Epoch 87/100
24/24 [==============================] - 0s 3ms/step - loss: 0.0449 - accuracy: 0.9917
Epoch 88/100


# 步驟6 評估與儲存模型

In [25]:
# 評估模型
print("\nTesting ...")
loss, accuracy = model.evaluate(X_test, Y_test)
print("測試集準確度 = {:.2f}".format(accuracy))


Testing ...
1/1 [==============================] - 0s 455ms/step - loss: 0.1183 - accuracy: 0.9667
測試集準確度 = 0.97


In [26]:
# 儲存 Keras 模型
print("Saving Model: iris.keras ...")

# "iris.h5" 改用 "iris.keras"
# UserWarning: You are saving your model as an HDF5 file via `model.save()`. 
# This file format is considered legacy. We recommend using instead the native Keras format, 
# e.g. `model.save('my_model.keras')`. saving_api.save_model(...

model.save("iris.keras")

Saving Model: iris.keras ...


In [27]:
# 使用儲存模型進行預測
from tensorflow import keras

In [28]:
model = Sequential()

In [29]:
model = keras.models.load_model("iris.keras")
model

In [30]:
model.compile(loss="categorical_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])

In [31]:
# 模擬新資料進行測試
np.random.seed(123)
samplesize = 10
new_sample = np.random.randint(30, size=samplesize)
print(new_sample)

[13  2 28  2  6 17 19 10 27 25]


In [32]:
# 自 test dataset 隨機抽取資料
X_newdata = X_test[new_sample,]
print(X_newdata)

[[ 1.03800476  0.55861082  1.10378283  1.71209594]
 [ 1.64384411  0.32841405  1.27429511  0.79067065]
 [ 0.4321654  -0.59237301  0.59224599  0.79067065]
 [ 1.64384411  0.32841405  1.27429511  0.79067065]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.32841405 -1.34022653 -1.3154443 ]
 [-0.17367395 -1.28296331  0.70592084  1.05393502]
 [ 0.4321654  -1.97355361  0.42173371  0.3957741 ]
 [-0.29484182 -0.13197948  0.42173371  0.3957741 ]
 [-0.90068117  1.01900435 -1.34022653 -1.18381211]]


In [33]:
Y_newdata = Y_test[new_sample,]
print(Y_newdata)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [34]:
loss, accuracy = model.evaluate(X_newdata, Y_newdata)
print("新資料集的準確度 = {:.2f}".format(accuracy))

1/1 [==============================] - 1s 690ms/step - loss: 0.0562 - accuracy: 1.0000
新資料集的準確度 = 1.00


In [35]:
# Y_pred = model.predict_classes(X_test)
# 'Sequential' object has no attribute 'predict_classes'
# 改用 model.predict()

Y_pred = np.argmax(model.predict(X_newdata), axis=1)
print(Y_pred)

1/1 [==============================] - 0s 204ms/step
[2 2 2 2 0 0 2 1 1 0]


In [36]:
Y_target = dataset[:,4][new_sample].astype(int)
print(Y_target)

[2 2 2 2 1 0 0 2 2 0]


In [37]:
# 混淆矩陣 (Confusion Matrix)
cm = pd.crosstab(Y_target,
                 Y_pred,
                 rownames=["Actual"],
                 colnames=["Predict"])
print(cm)

Predict  0  1  2
Actual          
0        2  0  1
1        1  0  0
2        0  2  4


In [38]:
test_accuracty = np.diag(cm).sum() / cm.to_numpy().sum()
print("模擬新資料之預測正確率:")
print(test_accuracty)

模擬新資料之預測正確率:
0.6


In [39]:
# end